version: '3.8'
services:
  devcontainer:
    build: 
      context: ..
      dockerfile: .devcontainer/Dockerfile
    volumes:
      - ../..:/workspaces:cached      
    # entrypoint: /usr/local/share/docker-init.sh
    command: sleep infinity
